### ISSUE TITLE
failed to build project

### ISSUE THREAD

**Issue by stalexxx** [cloudwebrtc/flutter-webrtc#147]
**Describe the bug**
Got this right away when trying to build 

Invalid plugin specification.
The flutter.plugin.platforms key cannot be used in combination with the oldflutter.plugin.{androidPackage,iosPrefix,pluginClass} keys.See: https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin

it starts working after I am commenting part of config:

```flutter:
  plugin:
    androidPackage: com.cloudwebrtc.webrtc
    pluginClass: FlutterWebRTCPlugin
    platforms:
      android:
        package: com.cloudwebrtc.webrtc
        pluginClass: FlutterWebRTCPlugin
      ios:
        pluginClass: FlutterWebRTCPlugin
      macos:
        pluginClass: FlutterWebRTCPlugin
```

**To Reproduce**

do anything, for example

flutter --no-color packages upgrade

**Platform information**
Mac os Mojave

* **Flutter version**: 1.9.1
* **Plugin version**: latest
* **OS**: any
* **OS version**:

**Comment by cloudwebrtc** [comment]
Now encountering a pubspec.yam conflict problem:
If switched to  flutter channel stable:

AndroidPackage / pluginClass must be placed
Under flutter.plugin., like this:

```yaml
flutter:
   plugin:
     androidPackage: com.cloudwebrtc.webrtc
     pluginClass: FlutterWebRTCPlugin
```

But if you switch to flutter channel master,
Such a configuration will throw an exception, you need to remove the androidPackage / pluginClass from
flutter.pulugin. removed and changed to

```yml
oldflutter:
   plugin:
     androidPackage: com.cloudwebrtc.webrtc
     pluginClass: FlutterWebRTCPlugin
```

**Comment by LinusU** [comment]
Hmm, I'm sorry for breaking this with Flutter master. It would be nice to support stable as well though 🤔 Maybe we could open an upstream issue with Flutter to allow the old style as well?

**Comment by cloudwebrtc** [comment]
@LinusU Yes, I also think this is a compatibility issue between Flutter stable/master channel.

**Comment by winwisely99** [comment]
SO is the code in the master branch setup to work with flutter channel master ?

Need to know...

**Comment by winwisely99** [comment]
Seems this works. Can master branch start to use this ? Or does that mess up people on stable ?

````
name: flutter_webrtc
description: Flutter WebRTC plugin for iOS/Android.
version: 0.1.7
author: cloudwebrtc <duanweiwei1982@gmail.com>
homepage: https://github.com/cloudwebrtc/flutter-webrtc

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.cloudwebrtc.webrtc
        pluginClass: FlutterWebRTCPlugin
      ios:
        pluginClass: FlutterWebRTCPlugin
      macos:
        pluginClass: FlutterWebRTCPlugin
      web:
        pluginClass: FlutterWebRTCPlugin
        fileName: lib/web/web_plugin.dart

oldflutter:
  plugin:
    androidPackage: com.cloudwebrtc.webrtc
    pluginClass: FlutterWebRTCPlugin
    
environment:
  sdk: ">=2.2.2 <3.0.0"

````

**Comment by CoreyCole** [comment]
In my pub-cache I had commit [~/.pub-cache/git/flutter-webrtc-f10d89d75e223eb932208114a4af866f67ebcd21/pubspec.yaml](https://github.com/cloudwebrtc/flutter-webrtc/commit/f10d89d75e223eb932208114a4af866f67ebcd21) and for some reason #156 was not reflected in there. I'm using a modified version of the flutter-webrtc-demo and this is my pubspec.yaml:
```yaml
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_webrtc:
    git:
      url: https://github.com/cloudwebrtc/flutter-webrtc.git
```
I was getting the error
```
✗ flutter pub get
Running "flutter pub get" in flutter-webrtc-demo...                 0.6s
Invalid plugin specification.
The flutter.plugin.platforms key cannot be used in combination with the oldflutter.plugin.{androidPackage,iosPrefix,pluginClass} keys.See:
https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin
```
To fix it, I went into the `~/.pub-cache` file and remove those two lines from the pubspec.yaml that were removed in #156:
```diff
flutter:
  plugin:
-    androidPackage: com.cloudwebrtc.webrtc
-    pluginClass: FlutterWebRTCPlugin
      platforms:
        android:
          package: com.cloudwebrtc.webrtc
```
