### ISSUE TITLE
MissingPluginException(No implementation found for method listen on channel FlutterWebRTC/dataChannelEvent0)

### ISSUE THREAD

**Issue by matthewmullin01** [cloudwebrtc/flutter-webrtc#158]
**Describe the bug**
Testing the mac build and I am running into this issue. 

Creating a dataChannel after creating a peer connection results in this error.

```
MissingPluginException (MissingPluginException(No implementation found for method listen on channel FlutterWebRTC/dataChannelEvent0))
```

Other platform methods work perfectly (addStream, createOffer, addCandidate etc).

I am on v0.2.2.

**To Reproduce**
Run the following for Mac and it'll crash when `createDataChannel` is called.
```
var peerConnection = await createPeerConnection(configuration, loopbackConstraints);

var dataChannelDict = new RTCDataChannelInit();
var dataChannel = await _peerConnection.createDataChannel('dataChannel', _dataChannelDict);

```
with 
```
Map<String, dynamic> configuration = {
  "iceServers": [
    {"url": "stun:stun.l.google.com:19302"},
  ]
};

final Map<String, dynamic> loopbackConstraints = {
  "mandatory": {},
  "optional": [
    {"DtlsSrtpKeyAgreement": false},
  ],
};
```

**Expected behavior**
A dataChannel to be established and not crash.

**Platform information**

* **Flutter version**: v1.13.3-pre.23
* **Plugin version**: v0.2.2
* **OS**: Mac 
* **OS version**: Catalina

**Comment by matthewmullin01** [comment]
Its awesome to see this plugin getting Mac and Web support so quickly (although I know its still early days so Im not getting too hyped just yet). Truly awesome stuff, and thanks for all the effort!

**Comment by cloudwebrtc** [comment]
Maybe a bug in the mac platform plugin.

**Comment by MuZiLee** [comment]
I have this problem now, is this bug not fixed yet?
```
environment: 
  sdk: '>=2.18.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  dio: 4.0.6
  get: 4.6.5
  logger: 1.1.0
  web_socket_channel: 2.2.0
  flutter_webrtc: 0.9.7
  fluttertoast: 8.0.9
  flutter: 
    sdk: flutter
```
